# Generated by Django 3.2.5 on 2021-07-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='phonetic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
