# Generated by Django 3.2.5 on 2021-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20210717_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='partOfSpeech',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
